commits_app/config/routes.rb
Rails.application.routes.draw do
  resources :commits
  root 'commits#index'
end

commits_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

commits_app/app/models/commit.rb
class Commit < ApplicationRecord
  def get_from_api
    Commit.destroy_all
    uri = URI("https://api.github.com/repos/#{author}/#{repo}/commits")
    response = HTTP.get(uri)
    commits_data = JSON.parse(response.body)
    commits_data.each do |element|
      name = element["commit"]["author"]["name"]
      email = element["commit"]["author"]["email"]
      date = element["commit"]["author"]["date"]
      sha = element["sha"]
      base = Commit.create(name: name, email: email, date: date, sha: sha)
    end
  end 
end

commits_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

commits_app/app/controllers/commits_controller.rb
class CommitsController < ApplicationController

  def index
    @commits = Commit.all
  end

  def new
    @commit = Commit.new
  end

  def create
    @commit = Commit.new(commit_params)
    @commit.get_from_api
    redirect_to @commit
  end

  def destroy
    @commit = Commit.find(params[:id])
    if @commit.destroy
      redirect_to root_path
    end
  end
  
  private
  def commit_params
    params.require(:commit).permit(:name, :email, :date, :sha, :author, :repo)
  end
end

commits_app/app/helpers/application_helper.rb
module ApplicationHelper
end

commits_app/app/helpers/commits_helper.rb
module CommitsHelper
end

commits_app/app/views/commits/index.html.erb
<h1>Results</h1>
<td><%= link_to 'Новый', new_commit_path %></td>
<table>
  <% @commits.each do |commit| %>
    <tr>
      <td><%= commit.name %></td>
      <td><%= commit.email %></td>
      <td><%= commit.date.try(:strftime, '%B %e, %Y') %></td>
      <td><%= commit.sha %></td>
      <td><%= link_to 'Удалить', commit_path(commit), method: :delete, data: { confirm: '' } %></td>
    </tr>
  <% end %>
</table>

commits_app/app/views/commits/new.html.erb
<%= form_for @commit, method: "post" do |f| %>
  <%= f.text_field :author, placeholder: "author" %><br>
  <br>
  <%= f.text_field :repo, placeholder: "repo" %><br>
  <br>
  <%= f.submit name: 'submit'%><br>
<% end %>

commits_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommitsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>